#!/usr/bin/env bash
# displays the content of the current directory in a list format

for file in *; do
    if [[ $file != .* ]]; then
        display="${file#*-}"
        echo "$display"
    fi
done
